version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.1.3
  python: circleci/python@0.2.1
  

jobs:
  build:
    docker:
      - image: cimg/python:3.8.6-browsers
    steps:
      - browser-tools/install-browser-tools
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: |
            python --version
            firefox --version
            python check-sel.py
          name: Test

workflows:
  main:
    jobs:
      - build

