version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.1.3
  python: circleci/python@0.2.1
  

jobs:
  build:
    docker:
      - image: cimg/python:3.8.6-browsers
    steps:
      - browser-tools/install-firefox
      - browser-tools/install-geckodriver
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: |
            mkdir /tmp/htmls
            cd lambda
            python test.py
          name: Fill Shield App

      - store_artifacts:
          path: /tmp/htmls

workflows:
  main:
    jobs:
      - build
  filldaily:
    triggers:
      - schedule:
          cron: "0 1 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - build

