version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.8.6-browsers
    steps:
      - checkout
      - run:
          command: |
            python --version
            python check-sel.py
          name: Test

workflows:
  main:
    jobs:
      - build

