version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.8.6-browsers
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: |
            python --version
            firefox --version
          name: Test

workflows:
  main:
    jobs:
      - build

